@startuml

!include ../design/prodsoft.wsd

title P-CHAT Component Diagram [Layers clean architecture: SPA + HTTP]
header  Without notification and socket components | Optional: ApiPresenter
footer Prodsoft - Moez SADOK @Copyright 2024

actor User 

package "FrameworksDrivers" #90baff\White;line:Black;line.bold {

    node "ClientBrowser" #afd8ff\White  {
        component [MainWebApp (SPA)\n(HttpClientAdapter + WebView \n PresenterUI)] as MainWebApp #transparent;line:Black;line.bold
        rectangle  SPAController $PRIMARY_LIGHT/White
        [UserInterface] $PRIMARY_LIGHT/LightGreen
        MainWebApp -[hidden]- UserInterface
    }

    package "Adapters" #baffd8\White;line:Black;line.bold {

        package "Application" #f88c8c/White;line:Black;line.bold {
            
            component Interactor #transparent;line:Black;line.bold{
                interface IRepository #f88c8c
                interface IUseCaseRequester #Gray
                rectangle UseCase #White
            }
            ' collections DTOs #White
            package "BusinessRules" #FDD835/White;line:Black;line.bold {
                [Entities] #FDD835/White
            }
        }

        component "PersistanceGateway" #transparent;line:Black;line.bold {
            interface IDataSource #baffd8
            rectangle Repository #transparent
            rectangle "DataMapper" as DataMapper #transparent
        }

        component "Controller\n" as Controller #transparent;line:Black;line.bold{
            interface IHttpController  $PRIMARY_LIGHT
            interface IPresenter #CDE711
            rectangle HttpServerAdapter  #transparent
            rectangle HttpClientAdapter  #transparent
        }

        component Presenter #transparent;line:Black;line.bold{
            interface IView #LimeGreen
            rectangle PresenterUI #transparent
        }

        component View #transparent;line:Black;line.bold{
            rectangle  WebView #transparent
        }
    }

    node "HttpServer" #afd8ff\White {
        component [MainServerApp\n(HttpServerAdapter + PersistanceGateway \n Application + Entities)] as MainServerApp #transparent;line:Black;line.bold
        rectangle APIController  $PRIMARY_LIGHT/White
        MainServerApp -down[hidden]- APIController
    }

    node "Database Server" #afd8ff\White {
        database AppDataBase $PRIMARY_LIGHT/afd8ff
        rectangle DataSource $PRIMARY_LIGHT/White
    }

}

User -right-> UserInterface : 1. triggerUserIntent()\n (navigation,click...)
UserInterface -right-> SPAController : 2. forwardUserRequest()
' HttpClientAdapter .right. HttpServerAdapter : 3. handleHttpRequest() \n12. returnHttpResponse()
SPAController .right. APIController :  3. handleHttpRequest() \n12. returnHttpResponse():json

APIController -down-> HttpServerAdapter :use
SPAController -down-> HttpClientAdapter :use

APIController -[hidden]up-> HttpServer

IHttpController -down-> IUseCaseRequester : 4. invokeUseCase() \n 11. deliverUseCaseResult()

UseCase -right-|> IUseCaseRequester

UseCase -right-> Entities  : 5. applyBusinessRules()

HttpServerAdapter -down-|>  IHttpController #Black

IRepository <-up- UseCase: 6. requestData() \n10. returnData()

Repository  -up-|>  IRepository #Black
Repository -right-> IDataSource : 7.queryOrPersistData()
Repository -left-> DataMapper : 9. mapToEntity()

DataSource -up-|> IDataSource #Black
DataSource -left-> AppDataBase : 8. runDBCommand()

' DataMapper -up-> BusinessRules: mapping() \n Optional DTOs
DataMapper -[hidden]up-> IView
DataMapper -up-> Entities: mapping() \n Optional DTOs

HttpClientAdapter -down-> IPresenter : 13. format()
PresenterUI -right-|>  IPresenter #Black
WebView --|> IView #Black
HttpClientAdapter -down-|>  IHttpController #Black

IView <-right- PresenterUI : 14. renderUi()
UserInterface -down-> WebView : 15. observe()
UserInterface  -up-> User : 16. presentToUser()

' MainServerApp -down-> Adapters : instanciate()
' MainServerApp -down-> Application : instanciate()
' MainServerApp -down-> BusinessRules : instanciate()

' MainWebApp -down-> View : instanciate()
' MainWebApp -down-> Presenter : instanciate()

' Using DTOs (to-check)
' collections DTOs #White (inside Application)
' DataMapper -up[hidden]-> Application
' DataMapper -up-> DTOs : useForMapping()
' DTOs -up-> Entities

' Application -left[hidden]- IHttpController
' SPAController .right[hidden]. APIController 
' IHttpController -[hidden]up-> Controller
' HttpServerAdapter -left[hidden]- HttpClientAdapter
' HttpServerAdapter .down[hidden]. UseCase 
' HttpClientAdapter -[hidden]-> PresenterUI  


@enduml
