@startuml

!include ../design/prodsoft.wsd

title Clean architecture component diagram [SPA + HTTP] 
header  No flow respect (usecase -> present) but clean archi respected (p.78) and Ipresenter stay on the interactor side
footer Prodsoft - Moez SADOK @Copyright 2024

actor User 

package "FrameworksDrivers" #90baff\White;line:Black;line.bold {

    node "ClientBrowser" #afd8ff\White  {
        component [MainWebApp (SPA)\n(HttpClientAdapter + WebJsonView \n PresenterUI)] as MainWebApp #transparent;line:Black;line.bold
        rectangle  SPAController $PRIMARY_LIGHT/White
        [UserInterface] $PRIMARY_LIGHT/LightGreen
        MainWebApp -[hidden]- UserInterface
    }

    package "Adapters" #baffd8\White;line:Black;line.bold {

        package "Application" #f88c8c/White;line:Black;line.bold {
            
            component Interactor #transparent;line:Black;line.bold{
                interface IRepository #f88c8c
                interface "IUseCaseRequester\n(InputPort)" as IUseCaseRequester #Gray
                rectangle UseCase #White
                interface "IPresenter\n(OutputPort)" as IPresenter  #CDE711
            }
            ' collections DTOs #White
            package "BusinessRules" #FDD835/White;line:Black;line.bold {
                [Entities] #FDD835/White
            }
        }

        component "PersistenceGateway" #transparent;line:Black;line.bold {
            interface IDataSource #baffd8
            rectangle Repository #transparent
            rectangle "DataMapper" as DataMapper #transparent
        }

        component "Controller\n" as Controller #transparent;line:Black;line.bold{
            interface IHttpController  $PRIMARY_LIGHT
            ' interface IPresenter #CDE711
            rectangle HttpServerAdapter  #transparent
            rectangle HttpClientAdapter  #transparent
        }

        component Presenter #transparent;line:Black;line.bold{
            interface IView #LimeGreen
            rectangle PresenterUI #transparent
            rectangle "ViewModel\n<<DataStructure>>"  as ViewModel #transparent;line:DarkGreen;
        }

        component View #transparent;line:Black;line.bold{
            rectangle  WebJsonView #transparent
        }
    }

    node "HttpServer" #afd8ff\White {
        component [MainServerApp\n(HttpServerAdapter + PersistenceGateway \n Application + Entities)] as MainServerApp #transparent;line:Black;line.bold
        rectangle APIController  $PRIMARY_LIGHT/White
        MainServerApp -down[hidden]- APIController
    }

   node "DatabaseServer" #afd8ff\White {
        database "DomainDataBase\n(Sql, NoSql, etc.)" as DomainDataBase $PRIMARY_LIGHT/afd8ff
        rectangle DataSource $PRIMARY_LIGHT/White
    }

}

User <-right-> UserInterface : 1. triggerUserIntent()\n (navigation,click...) \n\n 19. presentToUser()
UserInterface -right-> SPAController : 2. forwardUserRequest()
SPAController .right. APIController :  3. handleHttpRequest() \n14. returnHttpResponse():json

APIController -down-> IHttpController : 4.invoke() \n 13.returnJson()
SPAController -down-> IHttpController : 15. sendJson()

UseCase -up-|> IUseCaseRequester
HttpServerAdapter -down-> IUseCaseRequester :5. execute() \n12.returnResult()
UseCase -right-> Entities  : 11. applyBusinessRules()

HttpServerAdapter -up-|>  IHttpController #Black
HttpClientAdapter -up-|>  IHttpController #Black

' HttpClientAdapter -left-> IPresenter : 16. present()
' PresenterUI -right-|>  IPresenter #Black

HttpClientAdapter --> IPresenter : 16. present()
PresenterUI --|>  IPresenter #Black

IRepository <-up- UseCase: 6. requestData() \n10. returnData()
Repository  -up-|>  IRepository #Black
Repository -right-> IDataSource : 7.queryOrPersistData()
Repository -left-> DataMapper : 9. mapToEntity()

DataSource -up-|> IDataSource #Black
DataSource -left-> DomainDataBase : 8. runDBCommand()
DataMapper -[hidden]up-> IView
DataMapper -up-> Entities: mapping() \n Optional DTOs

WebJsonView --|> IView #Black

IView -right-> ViewModel 
ViewModel <-right- PresenterUI : 17. format()
UserInterface -down-> WebJsonView : 18. observe(vm)

' MainServerApp -down-> Adapters : instanciate()
' MainServerApp -down-> Application : instanciate()
' MainServerApp -down-> BusinessRules : instanciate()

' MainWebApp -down-> View : instanciate()
' MainWebApp -down-> Presenter : instanciate()

' Using DTOs (to-check)
' collections DTOs #White (inside Application)
' DataMapper -up[hidden]-> Application
' DataMapper -up-> DTOs : useForMapping()
' DTOs -up-> Entities

' Application -left[hidden]- IHttpController
' SPAController .right[hidden]. APIController 
' IHttpController -[hidden]up-> Controller
' HttpServerAdapter -left[hidden]- HttpClientAdapter
' HttpServerAdapter .down[hidden]. UseCase 
' HttpClientAdapter -[hidden]-> PresenterUI  


@enduml
