@startuml

!include ../design/prodsoft.wsd

title P-CHAT Component Diagram [Layers clean architecture: SSR + HTTP]
header  Without notification and socket components | Optional: ApiPresenter
footer Prodsoft - Moez SADOK @Copyright 2024

actor User 

package "FrameworksDrivers" #90baff\White;line:Black;line.bold {


    node "ClientBrowser" as ClientBrowser #afd8ff\White  {
     rectangle "HTMLRender\nHTTP" as Browser #White
    }

    package "Adapters" #baffd8\White;line:Black;line.bold {

        package "Application" #f88c8c/White;line:Black;line.bold {
            
            component Interactor #transparent;line:Black;line.bold{
                interface IRepository #f88c8c
                interface IUseCaseRequester #Gray
                rectangle UseCase #White
                 interface IPresenter #CDE711
            }
            ' collections DTOs #White
            package "BusinessRules" #FDD835/White;line:Black;line.bold {
                [Entities] #FDD835/White
            }
        }

        component "PersistanceGateway" #transparent;line:Black;line.bold {
            interface IDataSource #baffd8
            rectangle Repository #transparent
            rectangle "DataMapper" as DataMapper #transparent
        }

        component "Controller\n" as Controller #transparent;line:Black;line.bold{
            interface IHttpController  $PRIMARY_LIGHT
            ' interface IPresenter #CDE711
            rectangle HttpServerSSRAdapter  #transparent
        }

        component Presenter #transparent;line:Black;line.bold{
            interface IView #LimeGreen
            rectangle PresenterSSR #transparent
        }

        component View #transparent;line:Black;line.bold{
            rectangle  WebHtmlView #transparent
        }
    }

    node "HttpServer" #afd8ff\White {
        ' component [MainServerApp\n(HttpServerSSRAdapter + PersistanceGateway \n Application + Entities)] as MainServerApp #transparent;line:Black;line.bold
        component [MainServerApp] as MainServerApp #transparent;line:Black;line.bold
        rectangle APIController  $PRIMARY_LIGHT/White
        MainServerApp -down[hidden]- APIController
    }

    node "Database Server" #afd8ff\White {
        database AppDataBase $PRIMARY_LIGHT/afd8ff
        rectangle DataSource $PRIMARY_LIGHT/White
    }

}

ClientBrowser -[hidden]left-> HttpServer  
User <-.down.-> ClientBrowser : 1. setRoute(url) \n 14. seeHtmlPage()
Browser <-.left.-> APIController : 2. handleHttpRequest(url) \n13. returnHttpResponse(): html

' ClientBrowser -[hidden]left-> HttpServer  
' User <-.right.-> Browser : 1. setRoute(url) \n 16. seeHtmlPage()
' Browser <-.right.-> APIController : 2. handleHttpRequest(url) \n15. returnHttpResponse(): html


APIController -down-> HttpServerSSRAdapter : use

APIController -[hidden]up-> HttpServer

IHttpController -down-> IUseCaseRequester : 3. invokeUseCase() 

UseCase -up-> IPresenter : 10. formatUseCaseResult()

UseCase -left-|> IUseCaseRequester

UseCase -right-> Entities  : 4. applyBusinessRules()

HttpServerSSRAdapter -down-|>  IHttpController #Black

IRepository <-up- UseCase: 5. requestData() \n9. returnData()

Repository  -up-|>  IRepository #Black
Repository -left-> IDataSource : 6.queryOrPersistData()
Repository -left-> DataMapper : 8. mapToEntity()
DataSource -up-|> IDataSource #Black
DataSource -right-> AppDataBase : 7. runDBCommand()
DataMapper -up-> Entities: mapping() \n Optional DTOs

HttpServerSSRAdapter --> IPresenter 
HttpServerSSRAdapter -left-> IView : 12. getHTML()
PresenterSSR -up-|>  IPresenter #Black
WebHtmlView -left-|> IView #Black

IView <-- PresenterSSR : 11. renderUi()

@enduml
