@startuml

!include ../design/prodsoft.wsd

title P-CHAT Component Diagram [Layers clean architecture: SPA + HTTP]
header  Without notification and socket components | Optional: ApiPresenter
footer Prodsoft - Moez SADOK @Copyright 2024

actor User $SECONDARY

package "FrameworksDrivers" #90baff\White;line:Black;line.bold {

    node "ClientBrowser" #afd8ff\White  {

        component [MainFrontEnd\n(SPA: WebView + PresenterUI)] as MainFrontEnd
        rectangle  ClientController $PRIMARY_LIGHT
        [GUI] #LimeGreen
        MainFrontEnd -[hidden]- GUI
    }

    package "Adapters" #baffd8\White;line:Black;line.bold {

        package "Application" #f88c8c/White;line:Black;line.bold {
            interface IRepository #fa72ff
            collections UseCases #White
            ' collections DTOs #White

            package "BusinessRules" #FDD835/White;line:Black;line.bold {
                [Entities] #FDD835/White
            }

        }

        component "DbGateway" #transparent;line:Black;line.bold {
            interface IDataAccess #fa72ff/White
            rectangle ChatRepository #transparent
            rectangle "DataMapper\n(or ORM)" as DataMapper #transparent
        }

        component Controller #transparent;line:Black;line.bold{
            interface IHttpController  $PRIMARY_LIGHT
            interface IPresenter #CDE711
        }

        component Presenter #transparent;line:Black;line.bold{
            interface IView #LimeGreen
            rectangle PresenterUI #CDE711
        }

        component View #transparent;line:Black;line.bold{
            rectangle  WebView #LightGreen
        }
    }

    node "HttpServer" #afd8ff\White {
        component [MainBackEnd\n(DbGateway + App + Entities)] as MainBackEnd
        rectangle ServerController  $PRIMARY_LIGHT
    }

    node "Database Server" #afd8ff\White {
        database ChatDataBase #fc9eff/White
        rectangle DataAccess #fc9eff/White
    }

}

Application -left[hidden]- IHttpController

User -right-> GUI : 1. sendRequest
GUI -right-> ClientController : 2. Action:Routing,Click...
ClientController .right. ServerController : 3. handleHttpRequest() \n12. returnHttpResponse()
ServerController .down. UseCases : 4. call() \n 11. returnRes()
IHttpController -down-> UseCases
UseCases -right-> Entities  : 5. manageEntities()
ServerController -down-|>  IHttpController #Black

IRepository .up. UseCases : 6. dataReq \n10. dataRes
IRepository <-up- UseCases
ChatRepository  -up-|>  IRepository #Black
ChatRepository -left-> IDataAccess : 7.persistOrSelect()
ChatRepository -right-> DataMapper : 9. mapToEntity()
DataAccess -up-|> IDataAccess #Black
DataAccess -right-> ChatDataBase : 8. manageDB()
DataMapper -up-> Entities: mapping() \n Optional DTOs


PresenterUI --|>  IPresenter #Black
WebView -right-|> IView #Black
ClientController -down-|>  IHttpController #Black
ClientController --> PresenterUI  : 13. present()
IView <-right- PresenterUI : 14. display()
GUI -down-> WebView : 15. observe()
GUI  -up-> User : 16. seeResponse
IPresenter  -up[hidden]- IHttpController

' MainBackEnd -down-> Adapters : instanciate()
' MainBackEnd -down-> Application : instanciate()
' MainBackEnd -down-> BusinessRules : instanciate()

' MainFrontEnd -down-> View : instanciate()
' MainFrontEnd -down-> Presenter : instanciate()

' Using DTOs (to-check)
' collections DTOs #White (inside Application)
' DataMapper -up[hidden]-> Application
' DataMapper -up-> DTOs : useForMapping()
' DTOs -up-> Entities

@enduml
