@startuml

!include prodsoft.wsd

title P-CHAT Component Diagram 
footer Prodsoft - Moez SADOK @Copyright 2024

actor User $SECONDARY

package "Core/Adapters" $GARDIANT_LIGHT {
    interface IHttpController  $PRIMARY_LIGHT
    interface IPresenter #CDE711
}

package "Core"  $GARDIANT_LIGHT{
    interface IRepository #fa72ff
    interface INotifiyer $ACCENT_LIGHT\White
    collections UseCases #White
    
    [Entities] #FDD835

    package "NetworkGateway" #transparent;line:Black;line.bold {

        interface IChatServer  $PRIMARY_LIGHT/LightSeaGreen  
        interface IChatClient  $SECONDARY_VERY_LIGHT/LightGreen
    }
}

node "Client (Browser)" #fff7fe {
    interface IView #LimeGreen
    [PresenterUI] #CDE711
    [ClientController] $PRIMARY_LIGHT
    [GUI] #LimeGreen

    PresenterUI --|>  IPresenter
    ClientController --|>  IHttpController
    GUI --|> IView
}

node "Database Server" {
    database ChatDataBase #fa72ff
}

node "Notification Server" {
    [Notifiyer] $ACCENT_LIGHT\White
}

node "Http_Server" #d8fff5\White {
    [ServerController]  $PRIMARY_LIGHT
    [PresenterAPI] #CDE711
    ServerController --|>  IHttpController
    PresenterAPI --|>  IPresenter
}

node "Ws_Server" #CDE711/White {
    [ClientSocket] $SECONDARY_VERY_LIGHT/LightGreen
    [WsServer]  $PRIMARY_LIGHT/LightSeaGreen
}

User -down-> GUI : Send Request
GUI -right-> ClientController : Action:Routing,Click...

ServerController  <.--.> ClientController  : HTTP
ServerController <.-right-.> UseCases : requestUseCase(req)

Entities  <--  UseCases : manageEntities()

ClientController <.--.> WsServer : WS
IChatServer <|-left- WsServer
ClientSocket *-- WsServer
IChatClient  <|-left- ClientSocket
IChatClient *-- IChatServer
IChatClient <-down- Entities

IRepository <-up- UseCases  : getOrPersistData()
ChatDataBase  -up-|>  IRepository 

Notifiyer  -left-|>  INotifiyer
Entities -right-> INotifiyer : sendNotification(msg)

ServerController --> PresenterAPI : formatData()

ClientController --> PresenterUI  : present()
IView <-right- PresenterUI : display()

GUI  -up-> User : See response

' fake fidden line for design adaptation
ServerController  -up[hidden]- WsServer 
IPresenter  -up[hidden]- IHttpController 

@enduml
