@startuml

!include prodsoft.wsd

title P-CHAT Component Diagram - On memory
footer Prodsoft - Moez SADOK @Copyright 2024

actor Users $SECONDARY

node "Client" $BACKGROUND_LIGHT {
    interface IView #LimeGreen

    [GUI] #LimeGreen
    GUI --|> IView
}

package "Adapters" #77ff8b/White {
    interface IController  $PRIMARY_LIGHT
    interface IPresenter #CDE711

    [PresenterUI] #CDE711
    [ClientController] $PRIMARY_LIGHT

    PresenterUI -right-|>  IPresenter
    ClientController -right-|>  IController
}

package "Application" #ff7777/White {
    interface IRepository $PRIMARY_LIGHT
    interface INotifiyer $ACCENT_LIGHT\White
    collections UseCases #White

    [Entities] $SECONDARY_VERY_LIGHT
}

node "Database" {
    database ChatMemoryDB 
}

node "Notification" {
    [NotifiyerLogger] $ACCENT_LIGHT\White
}

Users -down-> GUI : Send Request
GUI -right-> ClientController : Action:Routing,Click...

IController <.-right-.> UseCases : handle()

Entities  <-down-  UseCases : manageEntities()

IRepository <-up- UseCases  : getOrPersistData()
ChatMemoryDB  -left-|>  IRepository

NotifiyerLogger  -left-|>  INotifiyer
Entities -right-> INotifiyer : send(msg)

ClientController -down-> IPresenter  : present()
IView <-right- PresenterUI : display()

GUI  -up-> Users : See response
ClientController -[hidden]- PresenterUI

@enduml
