@startuml

!include prodsoft.wsd

title P-CHAT Component Diagram - Layers (No APiPresenter)
footer Prodsoft - Moez SADOK @Copyright 2024

actor User $SECONDARY

package "FramworksDrivers" #90baff\White;line:Black;line.bold {

    node "ClientBrowser" #afd8ff\White  {
        [MainFrontEnd]
        [ClientController] $PRIMARY_LIGHT
        [GUI] #LimeGreen
        
        MainFrontEnd -[hidden]- GUI
   
    }

    package "Adapters" #d8fff5\White;line:Black;line.bold {

        package "Application" #f88c8c/White;line:Black;line.bold {
            interface IRepository #fa72ff
            collections UseCases #White

            package "BusinessRules" #FDD835/White;line:Black;line.bold {
                [Entities] #FDD835/White
                interface INotifiyer $ACCENT_LIGHT\White
            }

            component Notifiyer #transparent;line:Black;line.bold{
                interface INotif $ACCENT_LIGHT\White
                [NotifStrategy] #White
            }
        }

        package "Adapters/DbGateway" #d8fff5\White {
            [DataMapper] #transparent
        }

        package "Adapters/NotifGateway" #d8fff5\White {
            [NotificationFactory] #transparent
        }

        ' package "ContollerPresenter" #d8fff5\White {
            package Controller #transparent;line:Black;line.bold{
                interface IHttpController  $PRIMARY_LIGHT
                interface IPresenter #CDE711
                ' IHttpController -right- IPresenter
            }

            component Presenter #transparent;line:Black;line.bold{
               interface IView #LimeGreen
            '    [WebView] #LightGreen
              [PresenterUI] #CDE711
            }

            component View #transparent;line:Black;line.bold{
             
               [WebView] #LightGreen
            }
        ' }
    }

    node "HttpServer" #afd8ff\White {
        [MainBackEnd]
        [ServerController]  $PRIMARY_LIGHT
    }

    node "Database Server" #afd8ff\White {
        database ChatDataBase #fc9eff/White
    }

    node "External" #afd8ff\White{
        [PushNotificationServer] $ACCENT_LIGHT\White
        [MailServer] $ACCENT_LIGHT\White
    }

}

Application -up[hidden]- IHttpController
User -right-> GUI : Send Request
GUI -right-> ClientController : Action:Routing,Click...
GUI -down-> WebView : observe()
PresenterUI --|>  IPresenter
WebView --|> IView
ClientController --|>  IHttpController

ClientController --> PresenterUI  : present()
IView <-right- PresenterUI : display()
GUI  -up-> User : See response
IPresenter  -up[hidden]- IHttpController

ServerController --|>  IHttpController

IHttpController <.-right-.> UseCases : callUseCases()
ClientController <.-left-.> ServerController : handleHttpRequest()

IRepository <-up- UseCases  
' : getOrPersistData()
DataMapper  -up-|>  IRepository
DataMapper --> ChatDataBase

INotif   <|-- NotificationFactory
NotifStrategy -right-> INotif
NotifStrategy  -left-|>  INotifiyer
NotificationFactory --> PushNotificationServer
NotificationFactory --> MailServer

Entities -right-> INotifiyer : sendNotification(msg)
Entities  <-up-  UseCases : manageEntities()


@enduml
