@startuml

actor User #F06292

package "Adapters" {
    interface IController  #LightBlue
    interface IPresenter #CDE711
}
package "Core" {
    interface IRepository #FF5722
    interface INotifier #SpringGreen
    collections UseCases
    [Entities] #FDD835
    package "NetworkGateway" {
        interface IChatServer #SkyBlue
        interface IChatClient #MediumVioletRed
    }
}

' package "Core.NetworkGateway" {
    '     interface IChatServer #SkyBlue
    '     interface IChatClient #MediumVioletRed
    '
' }


node "Client (Browser)" {
    interface IView #Pink
    [PresenterUI] #CDE711
    [ClientController] #LightBlue
    [GUI] #Pink

    PresenterUI --|>  IPresenter
    ClientController --|>  IController
    GUI --|> IView
}

node "Database Server" {
    database ChatDataBase #FF5722
}

node "Notification Server" {
    [Notifier] #SpringGreen
}

node "Http_Server" {
    [ServerController]  #LightBlue
    [PresenterAPI] #CDE711
    ServerController --|>  IController
    PresenterAPI --|>  IPresenter
}

node "Ws_Server" {
    ' top to bottom direction
    [ClientSocket] #MediumVioletRed
    [WsServer] #SkyBlue

}

User -down-> GUI : Send Request
GUI -right-> ClientController : Action:Routing,Click...

ServerController  <.--.> ClientController  : HTTP
ServerController -right-> UseCases : callUseCase(req)/returnResult()

Entities  <--  UseCases : manageEntities()

ClientController <.--.> WsServer : WS
IChatServer <|-left- WsServer
ClientSocket *-- WsServer
IChatClient  <|-left- ClientSocket
IChatClient *-- IChatServer
IChatClient <-down- Entities


IRepository <-up- UseCases  : getOrPersistData()
ChatDataBase  -up-|>  IRepository

Notifier  -left-|>  INotifier
Entities -right-> INotifier : sendNotification(msg)

ServerController --> PresenterAPI : formatData()

ClientController --> PresenterUI  : present()
IView <-right- PresenterUI : display()

GUI  -up-> User : See response

' fake fidden line for design adaptation
ServerController  -up- WsServer #FFFFFF
IPresenter  -up- IController #FFFFFF

@enduml



' @startuml
' ' Packages / Component Diagram for chat system

' actor User #F06292

' package "User Interface" {
    '     package "View Package" {
        '         [View]
        '
    }
    '     View -up-|>  [GUI]
    '     View -up-|>  [CLI]
    '     View -up-|>  [API]
    '
}

' package "Controller Package" {
    '     [Controller] #CDE711
    '
}


' package "Use Case Interactor Package" {
    '     collections UseCases
    '
}

' package "Entity_Package" {
    '     [Entities] #FDD835
    '
}

' package "Repository Package" {
    '     [ChatRepository] #FF5722
    '
}

' package "Notifier Package" {
    '     [Notifier] #Green
    '
}

' package "Presentation Package" {
    '     [Presenter] #CDE711
    '
}

' package "WsServer Package" {
    '     [WsServer] #SkyBlue
    '
}

' User --> Controller : Send Request
' Controller --> UseCases : callUseCase(req)
' UseCases --> Entity_Package : manageEntities()
' ChatRepository  <-right-> UseCases  : getOrPersistData()
' UseCases -left-> Presenter : present()
' UseCases -left-> WsServer
' View <-down- Presenter : display()
' Entities -left-> Notifier : sendNotification(msg)
' View  <-right- User : See response

' @enduml





' @startuml
' Only components
' actor User #F06292

' collections UseCases
' [View] #Pink
' [GUI]  -down-|> View
' [CLI]  -down-|> View
' [API]  -down-|> View

' [Controller] #LightBlue
' [Entities] #FDD835
' [ChatRepository] #FF5722
' [Notifier] #SpringGreen
' [Presenter] #CDE711

' User --> Controller : Send Request
' Controller --> UseCases : callUseCase(req)
' UseCases --> Entities : manageEntities()
' ChatRepository  <-right-> UseCases  : getOrPersistData()
' UseCases -left-> Presenter : present()
' View <-down- Presenter : display()
' Entities -left-> Notifier : sendNotification(msg)
' View  -right-> User : See response

' @enduml