@startuml

!include prodsoft.wsd

title P-CHAT Entities Diagram 
footer Prodsoft - Moez SADOK @Copyright 2024

package "Entities" #33FFCC\356CAE{
    class UserEntity {
        - id: int
        - username: string
        - email: string
        - passwordHash: string
    }

    class RoomEntity {
        - id: int
        - name: string
        - participants: Set<ParticipantEntity>
        - lastMessages: List<MessageEntity>
        +register()
        +brodcast()
    }

    class ParticipantEntity {
        - id: int
        - user: UserEntity
        - room: RoomEntity
        - lastSeen: DateTime
        +enter()
        +leave()
        +receive()
        +send()
    }

    class MessageEntity {
        - id: int
        - content: string
        - sender: ParticipantEntity
        - timestamp: DateTime
        - room: RoomEntity
    }
}

package "Notifier" {
    interface INotify {
        + notify(): boolean
    }
}

package "ChatServer" {
    interface IChatClient {
        + getId(): int
        + receive(): void
    }

    interface IChatServer {
        + connect(): boolean
        + disconnect(): boolean
    }
}

IChatClient *-- IChatServer

RoomEntity *-right- ParticipantEntity
RoomEntity o--  MessageEntity
UserEntity *-- ParticipantEntity

ParticipantEntity o-right- INotify: has
ParticipantEntity o-- IChatClient: has if connected

@enduml
