@startuml

' title as titl Basic sucess sequence flow [without adapters and notifiyer] 
title Chat System Interaction
header A simple sequence diagram illustrating two users interacting
footer Success Flow [without adapters and notifiyer]

actor User1 #F06292
actor User2

participant WsChatServer
participant HttpServer #CDE711

control UseCases
entity Entities #FDD835
database ChatRepository #FF5722

User1 -> WsChatServer: Connect
' WsChatServer -> User1: Connection Acknowledged

User2 -> WsChatServer: Connect
' WsChatServer -> User2: Connection Acknowledged

User1 -> HttpServer: Send Message "Hello, User2!"
HttpServer -> UseCases: send()
UseCases -> UseCases: validate()
UseCases -> ChatRepository: save()
UseCases -> Entities : broadcast()
Entities -> WsChatServer: receive()
WsChatServer -> User2: Deliver Message "Hello, User2!"

@enduml
